whatwg/html

TEAM.md
Fixes #432. See #435 for bug discussions.
@annevk was this what you had in mind?
=> Update TEAM.md instructions on reviewing and bugs

TEAM.md
Addresses https://github.com/whatwg/html/issues/434
=> Explain how to automatically fetch PRs from forks

.htaccess, fonts/.htaccess, images/.htaccess, robots.txt
See https://github.com/whatwg/html-build/issues/33 for rationale for most and see https://twitter.com/xah_lee/status/685097707992563712 for rationale for scripting-1.html.
=> Redirect to the canonical URL for duplicate/old resources

images/asyncdefer.svg, images/content-venn.svg, images/parsing-model-overview.svg
https://github.com/whatwg/html/pull/570/files#r51091324
=> Clean up SVGs, relying on only viewBox, and no space before slash

README.md
Inspired by whatwg/dom and whatwg/fetch, adjusted for the harsh reality
of HTML.
=> Meta: improve pull request guidelines

a.js
Since the sequence of steps here is observable to author code,
optimizations like this need to be specified explicitly in the standard.
Fixes #1373.
/cc @kojiishi
=> Don't read observedAttributes if there is no attributeChangedCallback

README.md
See https://github.com/blog/2247-improving-collaboration-with-forks
=> Add info to README on allowing maintainer edits

.htaccess
=> Remove top-level ForceType text/html #507

demos/workers/stocks/search.cgi, demos/workers/stocks/stock.cgi
=> Add the .cgi files for the stock demos

CONTRIBUTING.md
=> Meta: add guidance on investigating across engines

README.md
See http://logs.glob.uno/?c=freenode%23whatwg&s=8%20Dec%202016&e=8%20Dec%202016#c1014108
=> Editorial: Re-add (minimal) build info to README

demos/workers/crypto/page.html
=> Editorial: bring back the crypto / startConversation() example

README.md
See https://github.com/whatwg/whatwg.org/pull/35
=> Meta: Update link for the WHATWG Code of Conduct

CONTRIBUTING.md
=> Meta: add contribution guidelines around the developer's edition

link-fixup.js
See https://github.com/whatwg/wattsi/pull/59
=> Meta: Fix link-fixup.js following a change in wattsi

FAQ.md
This change is minor cleanup for 5d512fe
=> Make some minor fixes to the FAQ

README.md
=> Meta: point to an external blame viewer

FAQ.md
=> Editorial: use implementer instead of implementor

404.html
Wording from https://github.com/whatwg/whatwg.org/blob/master/whatwg.org/404
=> Meta: update the 404 to invite filing issues instead of email

CONTRIBUTING.md
Helps with https://github.com/whatwg/meta/issues/43.
=> Meta: use "good first issue" as label

LICENSE
Depends on https://github.com/whatwg/wattsi/pull/67; as such "do not merge yet" until that's merged.
***
<a href="https://whatpr.org/html/3349/acknowledgements.html" title="Last updated on Jan 15, 2018, 11:43 PM GMT (43ae4c1)">/acknowledgements.html</a>  ( <a href="https://whatpr.org/html/3349/29d8343...43ae4c1/acknowledgements.html" title="Last updated on Jan 15, 2018, 11:43 PM GMT (43ae4c1)">diff</a> )
=> Meta: update for new WHATWG copyright

dev/styles.css
=> Dev edition: adjust styling for smaller screens

dev/styles.css
* Makes "bad" examples fit the current code block style, instead of
removing their background.
* Marks ABNF code as such. This will require html-build tweaks to have
an effect.
* Adds syntax highlighting styles to the dev edition. Closes #3755.
* Removes no-longer-necessary [hidden] rule, per
https://github.com/whatwg/whatwg.org/issues/220#issuecomment-409368787.
***
<a href="https://whatpr.org/html/3911/acknowledgements.html" title="Last updated on Aug 13, 2018, 5:49 PM GMT (2bbc27b)">/acknowledgements.html</a>  ( <a href="https://whatpr.org/html/3911/85e842a...2bbc27b/acknowledgements.html" title="Last updated on Aug 13, 2018, 5:49 PM GMT (2bbc27b)">diff</a> )
<a href="https://whatpr.org/html/3911/browsers.html" title="Last updated on Aug 13, 2018, 5:49 PM GMT …
=> Meta: update some syntax highlighting stuff

dev/styles.css
Follows https://github.com/whatwg/whatwg.org/pull/234.
Should be merged around the same time as that PR.
=> Meta: move common dev edition styles out

review-draft.sh
See also https://github.com/whatwg/whatwg.org/pull/237.
=> Meta: simplify Review Draft creation

review-draft.sh
Pretty sure this bit me the last time.
=> Meta: ensure master is up-to-date in review.sh

styles.css
***
<a href="https://whatpr.org/html/5536/acknowledgements.html" title="Last updated on May 13, 2020, 4:56 AM UTC (71f684c)">/acknowledgements.html</a>  ( <a href="https://whatpr.org/html/5536/c79c594...71f684c/acknowledgements.html" title="Last updated on May 13, 2020, 4:56 AM UTC (71f684c)">diff</a> )
<a href="https://whatpr.org/html/5536/browsers.html" title="Last updated on May 13, 2020, 4:56 AM UTC (71f684c)">/browsers.html</a>  ( <a href="https://whatpr.org/html/5536/c79c594...71f684c/browsers.html" title="Last updated on May 13, 2020, 4:56 AM UTC (71f684c)">diff</a> )
<a href="https://whatpr.org/html/5536/browsing-the-web.html" title="Last updated on May 13, 2020, 4:56 AM UTC (71f684c)">/browsing-the-web.html</a>  ( <a href="https://whatpr.org/html/5536/c79c594...71f684c/browsing-th …
=> Meta: make inline style sheet external

review-draft.sh
One line changes in source and two lines change relative to source in the copy that is made.
=> Meta: improve review-draft.sh

CONTRIBUTING.md, FAQ.md
***
<a href="https://whatpr.org/html/6747/index.html" title="Last updated on Jun 8, 2021, 5:55 AM UTC (9a22f91)">/index.html</a>  ( <a href="https://whatpr.org/html/6747/0e2bdcf...9a22f91/index.html" title="Last updated on Jun 8, 2021, 5:55 AM UTC (9a22f91)">diff</a> )
=> Meta: link to new Chat page

images/content-venn.svg, styles.css
See https://github.com/whatwg/whatwg.org/pull/392 for context.
=> Meta: match whatwg.org color contrast tweaks

FAQ.md
* …
* …
* …
* Chromium: …
* Gecko: …
* WebKit: …
* Deno (only for timers, structured clone, base64 utils, channel messaging, module resolution, web workers, and web storage): …
* Node.js (only for timers, structured clone, base64 utils, channel messaging, and module resolution): …
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
=> Fix an article 'an' to 'a' in FAQ

images/asyncdefer.svg, images/custom-element-reactions.svg, images/ircfog-modules.svg, images/outline.svg, images/parsing-model-overview.svg, images/sample-datalist.svg, images/sample-email-1.svg, images/sample-email-2.svg, images/sample-url.svg
Someone pointed out that one of the images in the spec had a transparent background but used black text, so it wasn't very visible. I went thru all the SVG images used by the spec, and made them all darkmode-aware, so they look nice now.
I'm also tagging all of these images with the class "darkmode-aware"; I'm going to accompany this with a PR to the WHATWG stylesheets that puts a white background on all SVG images that don't have that class. But that doesn't block this  PR; the rule won't hit any of the images in HTML. So feel free to merge this ahead of time.
***
<a href="https://whatpr.org/html/10257/acknowledgements.html" title="Last updated on Apr 5, 2024, 10:22 PM UTC (293bdfc)">/acknowledgements.html</a>  ( <a href="https://whatpr.org/html/10257/702119c...293bdfc/acknowledgements.ht …
=> Make all the SVGs darkmode-aware, and tag them as such.

.github/workflows/build.yml
This will get rid of a warning.
=> Meta: update GitHub Actions

PULL_REQUEST_TEMPLATE.md
See https://github.com/whatwg/spec-factory/pull/76 for context.
=> Meta: cover accessibility in the PR template

styles.css
See https://github.com/whatwg/whatwg.org/pull/457.
=> Meta: move .yesno styling to shared style sheet
