- README.md
- TEAM.md
I am not happy with how this bloats the readme. In fact I feel that merge policy in general, being for collaborators only, should probably not be in the readme.
What do we think of a COLLABORATORS.md?
Comments on content welcome.
> Add instructions for optimal PR merging

- .htaccess
Changes: 
* Add server configurations to the `.htaccess` file that make Apache serve certain resources compressed.
Right now, nothing served from https://html.spec.whatwg.org/ is compressed, e.g.:
```bash
$ curl -sSLvv -H 'Accept-Encoding: gzip, deflate' https://html.spec.whatwg.org/ -o /dev/null
*   Trying 208.113.236.128...
* Connected to html.spec.whatwg.org (208.113.236.128) port 443 (#0)
* TLS 1.0 connection using TLS_DHE_RSA_WITH_AES_256_CBC_SHA
* Server certificate: *.whatwg.org
* Server certificate: StartCom Class 2 Primary Intermediate Server CA
* Server certificate: StartCom Certification Authority
> GET / HTTP/1.1
> Host: html.spec.whatwg.org
> User-Agent: Mozilla/5.0 Gecko
> Accept: */*
> Accept-Encoding: gzip, deflate
> 
< HTTP/1.1 200 OK
< Date: Sat, 05 Sep 2015 20:03:17 GMT …
```
> Improve server configs

- images/asyncdefer.svg
Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=25943
Do not merge: it appears that the build script is rewriting all references to images/ into references to images.whatwg.org, which I don't have access to. @Hixie, what's the story there? Is the images directory on html.spec.whatwg.org pointless then?
> Add async/defer script loading diagram

- link-fixup.js
We already do this in 404.html. This helps fixing
https://github.com/whatwg/html-build/issues/33.
> Use absolute URL for fragment-links.js

- .htaccess
14111f62f041fec58a8a622ea042273e12b5f271 introduced a couple JPEG images with file extension .jpg, but we only set the mime type to image/jpeg for .jpeg files, not .jpg ones. This corrects that to allow both.
Thanks @izh1979 for pointing this out in #whatwg.
---
Tested this on a local apache and it works.
Alternate fixes:
- Rename the .jpgs to .jpeg
- Stop doing a top-level ForceType text/html, and just apply that to the "index" file. Then Apache's defaults can take over in most cases.
I went for the easiest thing.
> Fix recently-added JPEGs to be served correctly

- images/asyncdefer.svg
This adds support for `<script type="module">` for loading JavaScript modules, as well as all the infrastructure necessary for resolving, fetching, parsing, and evaluating module graphs rooted at such `<script type="module">`s.
This was spurred on by a request over in https://github.com/whatwg/loader/issues/83#issuecomment-166442597. This should take care of https://github.com/whatwg/loader/issues/83, https://github.com/whatwg/loader/issues/84, and https://github.com/whatwg/loader/issues/82. There is not much overlap with the current loader spec, which is primarily concerned with reflective modules and the author-customizable loading pipeline. This patch is much more about changing HTML's processing model for the script element, and integrating module execution the same way HTML currently …
> Add <script type="module"> and module resolution/fetching/evaluation

- TEAM.md
Accidentally resetting in the `master` branch could be annoying.
> Clarify where to do `git reset --hard`

- demos/workers/modules/filters.js
- demos/workers/modules/page.html
- demos/workers/modules/worker.js
/cc @ajklein @DigiTec @Constellation @jonco3
Builds on top of the editorial #607 (the first commit), and split into two commits for easier reviewing. This is a pretty simple spec, with most of the complication being in threading the CORS-awareness of modules through workers.
These commits also make it *very easy* to add CORS support to non-module workers, if people are interested in that while they are mucking around with this area of their implementation. If so let me know and I can tack on another commit doing so.
/cc @jungkees since you are probably going to want to do some of this for service workers too.
> Add worker modules

- images/content-venn.svg
content-venn.png does not include this text, fortunately.
Part of #52.
> Add picture to content-venn.svg

- images/content-venn.svg
- images/custom-element-reactions.svg
This upstreams custom elements into the HTML Standard, instead of having
them be in a separate spec that monkeypatches HTML extensively. This
builds on previous work in https://github.com/whatwg/dom/pull/204.
See https://rawgit.com/w3c/webcomponents/15a203c8393aef0df7223ab1d43406aa11a7e71e/spec/custom/index.html
for the source material, in particular the sections labeled "HTML+". All
changes while upstreaming were editorial in nature.
---
Review appreciated, especially in the form of pushing fixups to the branch.
> Add custom elements to HTML

- images/content-venn.svg
This reverts 29cf39d2163cfc85b67409f4e10390619ffb2b40 and many follow-up
refinement commits due to lack of implementer interest. Most of the use
cases served by `<style scoped>` are better served by `<style>` elements
inside a shadow root (although the features do work differently, in
that shadow DOM enforces isolation from the cascade, whereas `<style
scoped>` does not).
Fixes #552.
--
This could use some careful review with regard to the changed examples.
> Remove <style scoped>

- .travis.yml
This runs full build of the given source, so any problems which might occur on a real CI, will be reflected on the PRs as well.
Example of an execution can be seen here: https://travis-ci.org/RReverser/html/builds/130249854
Unfortunately, `build.whatwg.org` seems to be down at the moment (cc @domenic). Initially I thought it's a problem with the Travis setup, but can't ping it even locally.
Note: This still requires someone with admin rights to enable Travis for this repo, and then everything should just work.
Closes #1250.
> Enable Travis for auto-linting PRs

- images/custom-element-reactions.svg
As discussed in https://github.com/w3c/webcomponents/issues/186, there
are certain scenarios where custom element reactions could be enqueued,
but the custom element reactions stack is empty. The most prominent of
these is editing operations.
We solve this issue in two parts:
- First, introduce the backup element queue (similar to the old "base
element queue" concept; see
https://github.com/w3c/webcomponents/issues/457). This takes care of
cases like editing which cannot be solved in any other way.
- Also, we mandate that [CEReactions] be applied to nonstandard APIs
that modify the DOM, including a list of what we've identified so far.
Closes https://github.com/w3c/webcomponents/issues/186.
---
Careful review appreciated. /cc @dominiccooney @kojiishi @rniwa @annevk
> Take care of missing custom element reactions

- link-fixup.js
Please note this PR depends on another PR for wattsi (https://github.com/whatwg/wattsi/pull/25).
In https://github.com/whatwg/wattsi/pull/25, I propose to make fragment-links a json. To support fragment-lnks.json, link-fixup.js needs to be rewritten. Additionally, I found there are some rooms to improve in link-fixup.js. Notable changes include:
- Load fragment-links more speculatively
Current link-fixup.js waits DOMContentLoaded (and other resources and processes which block DOMContentLoaded) before loading fragment-links. However, it should redirect to new page as soon as possible in a situation where redirection is needed. To do so, the new link-fixup.js starts loading fragment-links if there are possibilities of redirection (location.hash is not empty).
In return for speculative …
> Rewrite link-fixup.js to adopt fragment-links.json

- TEAM.md
> Meta: simplify advice for pr/* branches

- CONTRIBUTING.md
- README.md
This is to get a pretty link when creating issues/PRs:
https://github.com/blog/1184-contributing-guidelines
> Meta: split CONTRIBUTING.md out from README.md

- .htaccess
This makes URLs like https://html.spec.whatwg.org/commit-snapshots/920c9183a7990968ecac1aeedae22391f3438791 properly display as text/html. This regressed in f7def432160c2fb13203c2a841da9c1932c13b8a when we got rid of the global ForceType.
> Meta: fix commit snapshots server config

- CONTRIBUTING.md
Since "Allow edits from maintainers" is checked by default, it seems
sufficient to link to the documentation, where the screenshot is from.
> Meta: simplify (shorten) contributing guidelines somewhat

- CONTRIBUTING.md
- TEAM.md
> Meta: appreciate web-platform-tests for normative changes

- .htaccess
This reverts commit e6c859c80aaa0318b15af500b9e57df2d0adb3ad. As
discussed in #1865, that change did not actually work, and instead we
had to add a new .htaccess file on the server. Closes #1865.
> Revert "Meta: fix commit snapshots server config"

- CONTRIBUTING.md
- TEAM.md
Prompted by https://github.com/w3c/web-platform-tests/pull/4034.
Part of #1849.
> Meta: add more guidance for how to handle test PRs

- images/sample-datalist.svg
- images/sample-email-1.svg
- images/sample-email-2.svg
As discussed in both #1811 and #1087, users, web developers, and
implementers find the spec's current vague phrasing around datalist UI
confusing. This has led to great implementation divergence, as
documented in the table in #1087. (That table also does not capture the
substring vs. prefix matching divergence.)
This attempts to provide more normative UI guidance and resolve the
issue, essentially taking the union of current display and search
choices. This will require changes from all browsers if they wish to
apply these suggestions.
Fixes #1811; fixes #1087.
/cc @travisleithead @nicksloan @jessi3py for your thoughts. My hope is that we can get general agreement from the people involved (and from the editors) that these UI suggestions are good. If so, we'll merge this, and then file …
> Add concrete suggestions for datalist display and matching

- 404.html
- link-fixup.js
This file was about 2.8MB and was always run on multipage/ but
the common case is to no-op. Instead XHR the fragment-links.json
file only when necessary.
Also fix 404.html to use the correct URL to link-fixup.js and use
`defer`.
Fixes #2026.
---
This depends on https://github.com/whatwg/wattsi/pull/31 and https://github.com/whatwg/html-build/pull/100
> Meta: Make link-fixup.js lightweight

- demos/canvas/blue-robot/index-idle.html
- demos/canvas/blue-robot/index.html
- demos/offline/clock/clock1.html
- demos/offline/clock/clock2.html
- demos/workers/crypto/page.html
- demos/workers/multicore/page.html
- demos/workers/multiviewer/page.html
- demos/workers/multiviewer/viewer.html
- demos/workers/primes/page.html
- demos/workers/shared/001/test.html
- demos/workers/shared/002/test.html
- demos/workers/shared/003/inner.html
- demos/workers/shared/003/test.html
- demos/workers/stocks/page.html
This ensures that the HTML documents in the `demos/` subdirectory follow the best practice of always including `<meta charset="utf-8">`.
> Meta: Add <meta charset=utf-8> to all demos/ files

- .travis.yml
This changes causes the Travis build to run the HTML checker on the `output/index.html` file and on all `output/multipage/*.html` files. The Travis build fails if the checker reports any errors.
> Meta: Make travis run HTML checker on all .html output

- .travis.yml
This change make Travis run the HTML checker vnu.jar with the right option and pathname arg needed to make it recurse through the output dir and only check HTML files.
> Meta: Make checker correctly recurse output dir

- .travis.yml
Travis needs Java8 to run the `vnu.jar` HTML checker. This change causes it to use the full path to the `java` binary, to ensure it always uses the right (Java8) one.
> Meta: Give Travis the full path to the java binary

- link-fixup.js
See https://github.com/whatwg/html/pull/2552#issuecomment-295360874
---
For `#the-worker's-lifetime`, in Firefox, `location.hash` returns `#the-worker%27s-lifetime` while Opera returns `#the-worker's-lifetime`.
I tested this locally to confirm that it works in Firefox and Opera.
> Meta: Fix link-fixup.js to support percent-escaped fragid

- .htaccess
There is at least some evidence that there used to exist a demo
offline/clock/clock.html, which has since been moved to
offline/clock/clock2.html. Such a file predates the incorporation of the
demos into this repository in cc0a94cfb006f06de63ee153821a382a4bfafd6b,
but we can add a redirect from the putative old URL just to be safe.
Closes #2620.
---
<del>Tagging "do not merge yet" until we get some clarity from @micbuffa about whether it should redirect to clock1.html or clock2.html (https://github.com/whatwg/html/issues/2620#issuecomment-299014110).</del> <ins>Done, it should be clock2.html</ins> Also, @micbuffa, what name would you like in the acknowledgments?
> Meta: add a redirect for the clock demo

- CONTRIBUTING.md
Given a single block element, "put it on a new line", not "on a newline".
> CONTRIBUTING.md: Change "newline" to "new line"

- html-dfn.js
This change enables the dfn popups in multipage output to show links to all
cross-references for a term across all files in the multipage output.
Not be merged to master as-is at this point; instead we first need to decide
where the multipage dfn.js script will live, the update the URL in the patch on
this PR branch.
For now, this PR just uses the URL for the dfn.js version on the branch at
https://github.com/whatwg/resources.whatwg.org/pull/56 branch (in the interest
of providing a way to run the build with multipage dfn.js enabled, and to
review the output).
Depends on:
* https://github.com/whatwg/resources.whatwg.org/pull/56
* https://github.com/whatwg/wattsi/pull/46
> Meta: Use cross-multipage dfn.js

- html-dfn.js
* Clicking anywhere but on a link caused cross-references to load.
Now fixed to only load if a `dfn` is clicked.
* Calling dfnLoad from dfnShow with a timeout is unnecessary with
the new setup.
* Clicking the permalink didn't close the panel.
* Clicking a cross-spec definition (in the Dependencies section)
didn't open the panel. It still doesn't show any references. (edit: https://github.com/whatwg/wattsi/issues/47)
* The click handlers were invoked in the wrong order; the onclick
on the links in the panel should be invoked first so that
event.stopPropagation() has an effect.
* The permalink was gone for the "No references" case.
* Made the permalink (and spec link, for cross-spec definitions)
appear immediately without waiting for fetching.
* Show an error message in the panel if the …
> Meta: Fix various regressions in html-dfn.js

- html-dfn.js
The intent here is that the dfn panel on multipage should act much
like it does on single-page. Following links in the panel should
let the panel stay open across page navigations. Closing the panel
or clicking on a new dfn, and then traversing through history,
should reflect the latest state.
Also fix subtle bugs that sometimes caused more than one panel to
be created, e.g., if a link in the panel is control-clicked.
> Meta: Persist dfn panel across multipage navigations

- dev/search.js
- dev/styles.css
Final steps for https://github.com/whatwg/html/issues/2779
> #2779 Dev edition: add back jump-to search

- dev/styles.css
* Adds an "About this specification" introduction, like the previous
version had. Closes #2780.
* Fixes the header logo positioning; the recent introduction of the
search box in cfb8b9e63541b035170c186b6957086ad9599de1 made the title
spill onto multiple lines, causing the logo to no longer be centered.
* Changes the <title> to "HTML Standard, Developer's Edition" to
distinguish it better from the full standard. whatwg/wattsi#50 remains
open for making the <title> more useful in general.
* Adds the full standard's favicon to the developer's edition too.
* Removes the useless Google fonts download, as we ended up deciding to
serve Droid Serif ourselves.
> Dev edition: add introduction, plus various tweaks

- FAQ.md
From https://wiki.whatwg.org/wiki/FAQ
Initial markdown produced using the already sanitized HTML from
https://github.com/whatwg/whatwg.org/pull/36 and
https://domchristie.github.io/to-markdown/ to convert it to
GitHub-flavored Markdown.
> Move the HTML parts of wiki FAQ here

- demos/workers/modules/page.html
Adds missing `<canvas>` element, and wraps the `<label>`s with `<p>`s. Closes #2908.
@Hermannovich, what name would you prefer in the acknowledgments?
> Fix and tweak module worker example

- dev/styles.css
Fixes #2794.
Requires a Wattsi pull request to be merged first; that will show up shortly.
Building the spec this way emits a number of warnings about things that are omitted. I am not sure what we should do about them:
```
Warning: Could not find ID parsing-xhtml-documents for annotation that uses URLs:
https://caniuse.com/#feat=xhtml
Warning: Could not find ID dom-a-rellist for annotation that uses URLs:
https://caniuse.com/#feat=rellist
Warning: Could not find ID dom-img-naturalwidth for annotation that uses URLs:
https://caniuse.com/#feat=img-naturalwidth-naturalheight
Warning: Could not find ID navigatorconcurrenthardware for annotation that uses URLs:
https://caniuse.com/#feat=hardwareconcurrency
Warning: Could not find ID stop-parsing for annotation that uses URLs: …
```
> Dev edition: display the caniuse panels

- link-fixup.js
Also do nothing if the path doesn't start with /multipage/ or /dev/.
Helps with #2934.
> Meta: Fix link-fixup to work when there's no fragment

- link-fixup.js
The Table of Contents link to index.html was redirected to
indices.html#index, and similarly all multipage pages without a
hash was being redirected (sometimes correctly, sometimes not).x
> Meta: make link-fixup.js only look at the path for 404s

- FAQ.md
This change touches older parts of the FAQ that have become outdated, making
adjustments to the wording of some parts to bring them into alignment with the
language in the current spec, and — for a couple of other parts that are no
longer as relevant — moving them into a "Legacy questions" section. Some general
copy-editing refinements are also included in the change.
> Bring outdated parts of the FAQ up to date

- images/ircfog-modules.svg
This allows preloading module script graphs. The processing model for
this turns out to be different enough that simply extending
rel="preload" is not a good option. Summary of why:
https://github.com/whatwg/fetch/issues/486#issuecomment-282044172
Closes whatwg/fetch#486.
Preview: https://output-kxakhvahwc.now.sh/multipage/links.html#link-type-modulepreload
---
/cc @whatwg/modules @yoavweiss
***
<a href="https://whatpr.org/html/2383/index.html" title="Last updated on Dec 8, 2017, 8:50 PM GMT (9ddb296)">/index.html</a>  ( <a href="https://whatpr.org/html/2383/dff66be...9ddb296/index.html" title="Last updated on Dec 8, 2017, 8:50 PM GMT (9ddb296)">diff</a> )
<a href="https://whatpr.org/html/2383/indices.html" title="Last updated on Dec 8, 2017, 8:50 PM GMT (9ddb296)">/indices.html</a>  ( <a …
> Add <link> rel="modulepreload"

- robots.txt
This was not picked up by the build script and it seems better to let the build script generate it anyway. See https://github.com/whatwg/html-build/issues/148.
> Meta: remove robots.txt (let the build script handle it)

- images/content-venn.svg
The shadow makes it harder to read, and doesn't really match
the style of where it's embedded.
> Editorial: remove text-shadow from content-venn diagram

- images/content-venn.svg
Multiple main elements are still allowed if all but one have the hidden attribute set.
This also slightly alters the definition of the body element as it effectively encompasses all content of a document, except for some metadata.
Fixes #100.
***
<a href="https://whatpr.org/html/3354/acknowledgements.html" title="Last updated on Jan 19, 2018, 11:52 AM GMT (8200648)">/acknowledgements.html</a>  ( <a href="https://whatpr.org/html/3354/97d8432...8200648/acknowledgements.html" title="Last updated on Jan 19, 2018, 11:52 AM GMT (8200648)">diff</a> )
<a href="https://whatpr.org/html/3354/dom.html" title="Last updated on Jan 19, 2018, 11:52 AM GMT (8200648)">/dom.html</a>  ( <a href="https://whatpr.org/html/3354/97d8432...8200648/dom.html" title="Last updated on Jan 19, 2018, 11:52 AM GMT …
> Restrict the main element to be used once per document

- dev/styles.css
This fixes an issue showing the search results at the end of the screen to the right instead of below the search box.
***
<a href="https://whatpr.org/html/3710/acknowledgements.html" title="Last updated on May 24, 2018, 1:31 AM GMT (4aaf642)">/acknowledgements.html</a>  ( <a href="https://whatpr.org/html/3710/ce8404f...4aaf642/acknowledgements.html" title="Last updated on May 24, 2018, 1:31 AM GMT (4aaf642)">diff</a> )
> Fix search results alignment

- demos/canvas/blue-robot/index-idle.html
- demos/canvas/blue-robot/index.html
Fixes https://github.com/whatwg/html/issues/3825.
It changes the canvas example comment to `100ms`.
> Changed Comment in Canvas Example

- README.md
This eliminates paint timing monkey patching, and fixes some minor issues with when we mark paint timing. 
This is necessary for us to correctly report event duration for the event timing spec. Issue [here](https://github.com/WICG/event-timing/issues/6). 
@domenic - you took a look at this [here](https://github.com/tdresser/html/pull/1).
***
<a href="https://whatpr.org/html/3923/acknowledgements.html" title="Last updated on Aug 16, 2018, 6:58 PM GMT (545cdbd)">/acknowledgements.html</a>  ( <a href="https://whatpr.org/html/3923/78741b7...545cdbd/acknowledgements.html" title="Last updated on Aug 16, 2018, 6:58 PM GMT (545cdbd)">diff</a> )
<a href="https://whatpr.org/html/3923/infrastructure.html" title="Last updated on Aug 16, 2018, 6:58 PM GMT (545cdbd)">/infrastructure.html</a>  ( <a …
> Eliminate paint timing monkey patching

- dev/styles.css
This was incorrectly moved to the shared style sheet in
df8dfc1b1c72a723285ba126e24577ba74a175d5.
> Meta: move one dev-edition-specific style back

- PULL_REQUEST_TEMPLATE.md
The idea here is to centralize important information for reviewers and onlookers in OP and relay expectations to those making the change.
Given the high volume of new external contributors HTML gets this is particularly important here, but if successful we could generalize this across the WHATWG.
> Meta: add a pull request template

- test.html
This PR simplifies the call graph around `internal module script graph fetching procedure`.
This PR makes top-level entry points of module loading
- `Fetch a module script graph`
- `Fetch an inline module script graph` (introduced by this PR)
- `Fetch a dynamic module script graph` (introduced by this PR)
- `Fetch a module worker script graph`
- `The fetch and process the linked resource algorithm for modulepreload links`
call `fetch the descendants of and instantiate`,
that calls `fetch the descendants of`,
that calls `internal module script graph fetching procedure`,
that calls `fetch the descendants of` recursively.
Previously, `internal module script graph fetching procedure` can be top-level or non-top-level,
and thus calls `fetch the descendants of and instantiate` or `fetch the …
> Editorial: refactor callers of internal module script graph fetching procedure

- CONTRIBUTING.md
Hi! 
When I raised my [first PR](https://github.com/whatwg/html/pull/5192) to the HTML spec, I didn't know how to wrap my text in VSCode. The contribution guide had instructions for Emacs, Vim, and Sublime. However, developers use many other text editors.
After searching HTML spec issues, I found a similar PR [here](https://github.com/whatwg/html/pull/5153). @domenic asked the author to wrap the text using https://output.jsbin.com/maferi. I used that website to format my own PRs to the HTML spec and found it very useful.
Thus, to assist fellow first-time HTML spec contributors, I'd like to link https://output.jsbin.com/maferi or a similar site in the contributing guidelines. Giving contributors a website as an option to format changes also has the advantage of being editor-agnostic.
**My …
> add recommended website to wrap text to 100 characters

- CONTRIBUTING.md
The spec was discussed in https://github.com/whatwg/html/issues/3236.
* Chrome
* Firefox is happy to put this into the specification, with the caveat that they may want to push for removing the allow-downloads flag later (in favor of just always blocking downloads): https://github.com/whatwg/html/pull/4293#issuecomment-594568779
* [wpt commit](https://github.com/web-platform-tests/wpt/commit/22d4bec70c4dc2572fce851a8cea3c0d5c7f5489)
* Chrome: [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=539938)
* Firefox: [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1558394)
* Safari: [bug](https://bugs.webkit.org/show_bug.cgi?id=198745)
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
***
<a …
> Add spec for 'sandboxed downloads' flag

- LICENSE
Helps with https://github.com/whatwg/sg/issues/102.
***
<a href="https://whatpr.org/html/5668/acknowledgements.html" title="Last updated on Jun 25, 2020, 10:45 AM UTC (27b0b66)">/acknowledgements.html</a>  ( <a href="https://whatpr.org/html/5668/b4fbe04...27b0b66/acknowledgements.html" title="Last updated on Jun 25, 2020, 10:45 AM UTC (27b0b66)">diff</a> )
> Meta: remove year from copyright line

- review-draft.sh
Helps with https://github.com/whatwg/sg/issues/124.
(I suspect we might want to move some of the Review Draft scripts into the whatwg/meta automated publishing infrastructure, but that can be tackled separately.)
***
<a href="https://whatpr.org/html/5697/acknowledgements.html" title="Last updated on Jul 2, 2020, 6:23 AM UTC (24af14c)">/acknowledgements.html</a>  ( <a href="https://whatpr.org/html/5697/8518025...24af14c/acknowledgements.html" title="Last updated on Jul 2, 2020, 6:23 AM UTC (24af14c)">diff</a> )
<a href="https://whatpr.org/html/5697/index.html" title="Last updated on Jul 2, 2020, 6:23 AM UTC (24af14c)">/index.html</a>  ( <a href="https://whatpr.org/html/5697/8518025...24af14c/index.html" title="Last updated on Jul 2, 2020, 6:23 AM UTC (24af14c)">diff</a> )
> Meta: separate IPR and point to Review Drafts there

- demos/canvas/blue-robot/index-idle.html
- demos/canvas/blue-robot/index.html
- demos/offline/clock/clock1.html
- demos/offline/clock/clock2.html
- demos/workers/crypto/page.html
- demos/workers/modules/page.html
- demos/workers/multicore/page.html
- demos/workers/multiviewer/page.html
- demos/workers/multiviewer/viewer.html
- demos/workers/primes/page.html
- demos/workers/shared/001/test.html
- demos/workers/shared/002/test.html
- demos/workers/shared/003/inner.html
- demos/workers/shared/003/test.html
This silences most of the (well-deserved!) warnings from the HTML
checker.
> Add lang="en" to all the demo pages

- FAQ.md
Mainly more HTTPS, but also to account for the agreement with the W3C.
> Meta: update the HTML FAQ

- html-dfn.js
- styles.css
This change removes the HTML-specific styles dealing with the dfn panels, and changes `html-dfn.js` to have those panels match Bikeshed's output more closely. The particular changes are:
- Panels have the `"dfn-panel"` class, rather than `"dfnPanel"`. They also have the `"on"` class, to make them visible.
- ~Dfn panels get created as children of body rather than of the dfn element, and their position is set when they are created.~
- Moved panels gain the "activated" class, instead of gaining inline styles.
- The elements that can open a dfn panel when clicked now include headings with the `"data-dfn-type"` attribute (corresponding to a `"dfn"` attribute in the source), ~and every such element is populated with the `"dfn-paneled"` class when the script first runs.~
- ~Removes the …
> Meta: Update the dfn panels to match Bikeshed's output more closely

- FAQ.md
Use more HTTPS and drop obsolete HTML Differences reference.
***
<a href="https://whatpr.org/html/6311/links.html" title="Last updated on Jan 19, 2021, 10:27 AM UTC (05adaa1)">/links.html</a>  ( <a href="https://whatpr.org/html/6311/a9d2511...05adaa1/links.html" title="Last updated on Jan 19, 2021, 10:27 AM UTC (05adaa1)">diff</a> )
<a href="https://whatpr.org/html/6311/references.html" title="Last updated on Jan 19, 2021, 10:27 AM UTC (05adaa1)">/references.html</a>  ( <a href="https://whatpr.org/html/6311/a9d2511...05adaa1/references.html" title="Last updated on Jan 19, 2021, 10:27 AM UTC (05adaa1)">diff</a> )
<a href="https://whatpr.org/html/6311/window-object.html" title="Last updated on Jan 19, 2021, 10:27 AM UTC (05adaa1)">/window-object.html</a>  ( <a …
> Meta: minor references cleanup

- demos/workers/modules/page.html
This code example appends a canvas to the existing canvas#output, which is not valid. So I replace the canvas#output to div#output.
Then I changed output.appendChild(canvas) to output.replaceChildren(canvas).
* …canvas#output, - div#output
* …output.appendChild(canvas) -  output.replaceChildren(canvas).
* …
* Chrome: …
* Firefox: …
* Safari: …
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
***
<a href="https://whatpr.org/html/6404/acknowledgements.html" title="Last updated on Feb 23, 2021, 5:27 PM UTC (2e96a28)">/acknowledgements.html</a>  ( <a href="https://whatpr.org/html/6404/fd40465...2e96a28/acknowledgements.html" title="Last updated on Feb 23, 2021, 5:27 PM UTC (2e96a28)">diff</a> )
> web worker doc example typo, nesting canvas elements

- dev/styles.css
Editorial change only, updating <http://developers.whatwg.org/introduction.html#typographic-conventions> to directly use HTTPS.
> Change link for typographic conventions to HTTPS

- CONTRIBUTING.md
- FAQ.md
This is an attempt at addressing the discussion starting at https://github.com/whatwg/html/issues/6003#issuecomment-805389170.
It ensures browsers only vary on a single boolean, "PDF viewer supported". Then, it:
- Standardizes a new `navigator.pdfSupported` property which exposes that boolean directly.
- Makes the legacy `navigator.plugins` and `navigator.mimeType` interfaces expose a uniform set of `Plugin` and `MimeType` objects, across every browser, in one of two configurations (depending on the PDF viewer supported boolean).
For PDF viewer supported UAs, the resulting structure is:
- 5 `Plugin` objects, named (in order) "PDF Viewer", "Chrome PDF Viewer", "Chromium PDF Viewer", "Microsoft Edge PDF Viewer", "WebKit built-in PDF".
- `description`: "Portable Document Format" (like …
> Restore navigator.plugins and navigator.mimeTypes as PDF-focused

- FAQ.md
Closes #3655. Closes #5121. Closes #6049.
***
<a href="https://whatpr.org/html/7071/named-characters.html" title="Last updated on Sep 20, 2021, 3:04 PM UTC (1b37f8c)">/named-characters.html</a>  ( <a href="https://whatpr.org/html/7071/92a152c...1b37f8c/named-characters.html" title="Last updated on Sep 20, 2021, 3:04 PM UTC (1b37f8c)">diff</a> )
> Note that we will not add new named character references

- FAQ.md
I’m just making a simple correction to spelling, as encouraged by the contribution guidelines.
> Correct misspelling of “marketplace”

- images/outline.svg
This PR is an attempt to bring the HTML spec in line with the [decade+ old reality](https://html5accessibility.com/stuff/2022/04/05/12-years-beyond-a-html-joke/) of non-implementation of the outline algorithm in User Agents and the continued presence of misleading content in the HTML spec relating to the outline algorithm.
**Notes:**
- Removed outline algorithm section
- Updated `hgroup` definition to reflect what it actually does/is
- Updated numerous code examples to reflect Heading semantics as implemented in User agents
- Updated/removed outline related cruft.
Relates to:
- https://github.com/whatwg/html/issues/83 
- https://github.com/whatwg/html/pull/3499
- https://github.com/whatwg/html/pull/6462
- https://github.com/w3c/htmlwg/issues/22
The CSS UA styles _partial_ implementation …
> replace current outline algorithm with one based on heading levels

- styles.css
Helps with #4592.
***
<a href="https://whatpr.org/html/8026/dom.html" title="Last updated on Jun 22, 2022, 7:12 PM UTC (8cde724)">/dom.html</a>  ( <a href="https://whatpr.org/html/8026/9af0600...8cde724/dom.html" title="Last updated on Jun 22, 2022, 7:12 PM UTC (8cde724)">diff</a> )
> Editorial: use <iframe>, not <object>, for content-venn.svg

- styles.css
This imports much of the specification from https://wicg.github.io/import-maps/. The main deltas are:
* Does not include support for external import maps, since nobody has implemented these yet. This allows a good deal of simplification, such as by changing "acquiring import maps" + "pending import map script" + "wait for import maps" to a single "import maps allowed" boolean, or integrating "register an import map" into "execute the script element". If a src="" attribute is present on an importmap script element, then an error event is fired.
* Does not include any support for non-Window import maps. The spec draft included stub support for those, with other globals always having an empty import map. This instead ties import maps to Windows directly. If we revisit that in the future we …
> Add basic import maps support

- styles.css
Previously the task had no specified task source.
Because task sources are not very observable, this is mostly good spec hygiene.
* Probably this is fine? Task sources are not very testable in general. By code inspection, Gecko and WebKit use some sort of "run on the main thread" call (WebKit might fire these sync in some cases??). Chromium uses the "DOM manipulation task source" which is why I chose that one, instead of e.g. the networking task source.
* I don't think we need tests here, since task source ordering is not really testable. Maybe we could do basic tests that these are fired async instead of sync, but that would be more good-citizenship-while-we're-in-the-area tests, not testing this change in particular
* Chrome: N/A
* Firefox: N/A I think
* Safari: N/A I think
* Deno (only …
> Use "queue an element task" properly in script preparation

- .github/workflows/build.yml
Looks like 22.04 will be the new ubuntu-latest soonish: https://github.com/actions/runner-images.
Align actions/checkout with other WHATWG standards.
> Meta: adopt new Ubuntu in build.yml

- dev/styles.css
Part of https://github.com/whatwg/whatwg.org/issues/401.
Should merge shortly after https://github.com/whatwg/whatwg.org/pull/408 .
***
<a href="https://whatpr.org/html/8473/acknowledgements.html" title="Last updated on Nov 7, 2022, 10:40 AM UTC (ffffd49)">/acknowledgements.html</a>  ( <a href="https://whatpr.org/html/8473/53346e4...ffffd49/acknowledgements.html" title="Last updated on Nov 7, 2022, 10:40 AM UTC (ffffd49)">diff</a> )
<a href="https://whatpr.org/html/8473/browsers.html" title="Last updated on Nov 7, 2022, 10:40 AM UTC (ffffd49)">/browsers.html</a>  ( <a href="https://whatpr.org/html/8473/53346e4...ffffd49/browsers.html" title="Last updated on Nov 7, 2022, 10:40 AM UTC (ffffd49)">diff</a> )
<a href="https://whatpr.org/html/8473/browsing-the-web.html" title="Last updated on …
> Meta: use <p> for subheading instead of <h2>

- FAQ.md
* Remove advice on using `<h1>`, per 6682bdeee6fb08f5972bea92064fe250f1b4ec9c.
* Update the mention of W3C forks, since all known ones redirect nowadays.
* Update "WHATWG and the W3C HTML WG" section to reflect the Memorandum of Understanding, and moved it toward the bottom since it's less important these days.
> Meta: update outdated parts of the FAQ

- styles.css
Hi!
I plan to propose a refactor to the import-related host hooks of ECMA-262, and this PR shows how it would affect HTML.
Currently, ECMA-262 has two host hooks:
- `HostResolveImportedModule(referrer, specifier)`, which synchronously returns the Module Record corresponding to the `(referrer, specifier)` pair;
- `HostImportModuleDynamically(referrer, specifier)`, used for dynamic `import()`, which asynchronously loads the Module Record corresponding to `(referrer, specifier)` and all its dependencies, calls `.Link()`/`.Evaluate()` on it and then "returns" to ECMA-262 by calling `FinishDynamicImport`.
We are working on three ECMA-262 proposals related to modules, and each one of them has needs that are not satisfied by the existing layering:
- [Module …
> [ECMA-262 layering] Refactor import-related host hooks

- images/content-venn.svg
Closes #5811.
This new element allows authors to express the semantics of "a set of form controls or other content related to performing a search or filtering operation".
This is an especially desired semantic because it is something that an ARIA landmark role exists for (`role="search"`), but today can only be expressed with ARIA. Adding a dedicated element allows authors to follow the [first rule of ARIA](https://w3c.github.io/using-aria/#rule1) (~ "don't use ARIA if you can avoid it") and is part of the [co-evolution process](https://w3c.github.io/aria/#co-evolution) between ARIA and HTML.
Please see [the pull request preview](https://whatpr.org/html/7320/grouping-content.html#the-search-element) for web-developer focused details on usage and examples.
Some notable design choices:
- …
> Add the <search> element

- .github/workflows/build.yml
Docker Hub was planning to sunset their free plan: https://www.docker.com/developers/free-team-faq/. Although they have backed down from doing this, it still seems better to centralize our infrastructure dependencies on GitHub.
Wattsi and html-build have been successfully published to the GHCR. This commit moves HTML's continuous integration step to depend on the GHCR version of html-build, instead of the Docker Hub version.
> Meta: move to GitHub Container Registry

- .github/workflows/build.yml
Fixes https://github.com/whatwg/html/issues/9196
Fixes https://github.com/whatwg/html/issues/9197
Fixes https://github.com/whatwg/html/issues/9319
- Fix a case where a beforetoggle event handler opens a new popover
- Stop firing beforetoggle events when there are nested calls to showPopover or hidePopover due to script
This PR accounts for these 4 chromium patches whose commit messages have additional context:
- https://chromium-review.googlesource.com/c/chromium/src/+/4459795
- https://chromium-review.googlesource.com/c/chromium/src/+/4461952
- https://chromium-review.googlesource.com/c/chromium/src/+/4472129
- https://chromium-review.googlesource.com/c/chromium/src/+/4471675
* Chrome
* WebKit
* https://github.com/web-platform-tests/wpt/pull/39647
* …
> Improve popover event handling in nested showing and hiding

- CONTRIBUTING.md
Before I made my first editorial PR I was searching the `CONTRIBUTING.md` for information about the syntax used in the `source` file. However I was obviously only skimming the file because I missed the last link in the the following paragraph:
> Note that `source` is written in a dialect of HTML, which is eventually compiled into the deployed standard by a tool called [Wattsi](https://github.com/whatwg/wattsi). Documentation for this dialect can be found [in the Wattsi repository](https://github.com/whatwg/wattsi/blob/main/Syntax.md).
Probably because of the undescriptive link label "in the Wattsi repository". This PR therefore rewords this paragraph to:
> Note that `source` is written in [Wattsi Syntax](https://github.com/whatwg/wattsi/blob/main/Syntax.md), a dialect of HTML, which is …
> Meta: make Wattsi Syntax link more prominent in CONTRIBUTING.md

- styles.css
This change fixes dark mode bugs in the module script fetching diagram
and in the named character references table.
***
<a href="https://whatpr.org/html/10144/webappapis.html" title="Last updated on Feb 19, 2024, 5:46 AM UTC (4252552)">/webappapis.html</a>  ( <a href="https://whatpr.org/html/10144/39ec692...4252552/webappapis.html" title="Last updated on Feb 19, 2024, 5:46 AM UTC (4252552)">diff</a> )
> Meta: Dark mode fixes

- styles.css
Finishes porting the last few manual colors in `styles.html` to be darkmode-aware. (`dev/styles.html` is already darkmoded)
* Pulled out the "bad example" text color (same in both light and dark, but good for all colors to live together)
* Add darkmode color for the .yesno tables (switched from a lightmode yellow to a darkmode "WHATWG green, but slightly darker", since it's just meant to help draw the eye a little when quickly scanning a large table)
* Removed `.glyph.control` style entirely; it doesn't appear to be used anywhere in the spec.
* Pulled the "abstract img" colors out (again, same in both light and dark)
* Removed the manual bg/text colors from jake diagrams, chose a set of dark cell colors to complement the lightmode pastels.
> More darkmode coloring. Fixes #10141

- styles.css
Changed a single CSS line in `styles.css` and added a name to the acknowledgements section, as prompted in `CONTRIBUTING.md`. This is a fix for issue #10618.
This is a fairly trivial fix related to the site's user interface, so there are no tests or related implementation bugs.
> Fix small CSS-related user interface issue on spec page (Issue #10618)

- CONTRIBUTING.md
- var-click-highlighting.js
(I'm creating this in draft mode, because at this stage it's more of a discussion-starter than a solid proposal.)
In issue #10483, @Domenic raises the possibility of wrapping the HTML spec's algorithms in `<div algorithm>` (as in Bikeshed specs). This PR does something approximating that.
The first commit is a minor markup change that was originally in PR #11379, but fell out when I withdrew the `<hN>`-related commits.
The second commit just adds some linebreaks, so that the main commit has a cleaner diff.
In the main commit, I add 2269 `<div>...</div>` pairs.
Each `<div>` start tag has one or both attributes:
- `var-scope`
- `algo="..."`
(11 have only `var-scope`, 1081 have only `algo`, 1177 have both.)
`var-scope` means: this `div` is a scope for `<var>` elements. (The main commit also …
> Markup: Wrap algorithms in <div> tags
